# Do not modify this file!  It was generated by ‘nixos-generate-config’
# on the fresh VM install (2026-08-25) and may be overwritten by future
# invocations. Please make changes in hosts/nixos-test/default.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "virtio_scsi" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/56f53368-b85a-49f0-8288-4d04d55cfa68";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/56f53368-b85a-49f0-8288-4d04d55cfa68";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/56f53368-b85a-49f0-8288-4d04d55cfa68";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5299-7F99";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7ea2c2f2-df0f-4499-b3be-901a0092fcbb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
